### ISSUE TITLE
Informative plot file names

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/flywheelMRSupport#4]
Great job getting the PDFs loaded on flywheel. I think more informative file names would be useful, however. Instead of “T1.pdf” how about “mriqcSummary_T1.pdf” and so on.

**Comment by nikhilvamsi31** [comment]
I just edited the code to have more informative files names. If you check on the qcplots branch I also pushed a commit with getQCmetrics converted into a function called analyzeQCmetrics.

**Comment by gkaguirre** [comment]
Looking good
